### ISSUE TITLE
Cakeshop not working as intended with external quorum nodes

### ISSUE THREAD

**Issue by nottherealbatman** [jpmorganchase/cakeshop#23]
#### Description of problem
Trying to connect Cakeshop with a Quorum node

#### Expected behavior
Cakeshop works like the standalone dockerized version.

#### Actual behavior
Not all of the functionalities are working. A lot of RPC errors.

#### Steps to reproduce the behavior
in `application.properties`
change the following
```
geth.auto.start = false
geth.auto.stop = false
geth.url = 'url of external rpc node'
```

#### System information
Cakeshop version or commit hash: v0.9.1
```
Geth
Version: 1.5.0-unstable
Git Commit: 82a140abbb3ca706b5cdc95d63b345fdc115a3a9
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=/home/ubuntu/work
GOROOT=/usr/lib/go-1.6
```

Cakeshop OS & Version: Windows/Linux/OSX
Ubuntu 16.04
Browser OS & Version: Windows/Linux/OSX MSIE/Chrome/Firefox/Safari
Firefox, Chrome both latest version
#### Backtrace/logs
[Gist url](https://gist.github.com/nottherealbatman/417f7afc261f1e635a5f5d53dd7a6133)

### Extra info 
The node which cakeshop connects to is started with the following command
`geth --datadir quorum-data --permissioned --voteaccount "0x6c5ec8b0ac92bc4900e46428169c26fc2b7c7817" --votepassword "" --ipcdisable --rpc --nodiscover --rpcaddr "<address removed>" --rpcapi eth,web3,personal --blockmakeraccount "0x6c5ec8b0ac92bc4900e46428169c26fc2b7c7817" --blockmakerpassword "" --verbosity 6 console
`

**Comment by tylobban** [comment]
Hi @nottherealbatman, there are a number of errors in the log, some are admin related since it looks like you didn’t pass the admin API on startup. The default APIs consumed by cakeshop are: admin,db,eth,debug,miner,net,shh,txpool,personal,web3. You can see them in the default applications.properties file. Some other issues being logged have been addressed on the Quorum [upgrade fork](https://github.com/fixanoid/cakeshop/tree/quorum-ui) or you may try the v0.10.0 [pre-release](https://github.com/fixanoid/cakeshop/releases).

**Comment by andytudhope** [comment]
Hi Ty. I am running into similar issues trying to attach cakeshop to a network of 3 nodes that I have set up using Coenie's Quorum Network Manager. Have followed the step in the wiki and above closely. ran into soem strange `Text file busy` errors ,but must have been my own fault. However, I have now found the correct RPC url to use for connection, but am still getting a strange error:
```
GethHttpServiceImpl - RPC call failed - EOFException: \n not found: size=0 content=...
[INFO ] 2017-06-06 10:01:14.346 [main] BlockchainInitializerTask - Contract registry address not found
[INFO ] 2017-06-06 10:01:14.346 [main] BlockchainInitializerTask - ContractRegistry not found on chain
[INFO ] 2017-06-06 10:01:14.350 [main] BlockchainInitializerTask - Deploying ContractRegistry to chain
[ERROR] 2017-06-06 10:01:20.469 [main] GethHttpServiceImpl - RPC call failed - EOFException: \n not found: size=0 content=...
[ERROR] 2017-06-06 10:01:20.470 [main] ContractRegistryServiceImpl - Error deploying ContractRegistry to chain: RPC call failed
com.jpmorgan.cakeshop.error.APIException: RPC call failed
```

Could you enlighten me as to what I've managed to muck up this time? ;)

**Comment by tylobban** [comment]
Hi @andytudhope - can you confirm:
1) is this on the pre-release or current cakeshop release?
2) the RPC APIs that the node was started with? Per my comment above, the Quorum node needs to be started with the following apis:  admin,db,eth,debug,miner,net,shh,txpool,personal,web3

**Comment by andytudhope** [comment]
1) Pre-release
2) `--rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum` so may need to remove the last there? Might also be that `rpcaddr` now that I think about it...

**Comment by andytudhope** [comment]
It's this script that gets run by the Network Manager to start the BM and BV nodes: https://github.com/ConsenSys/QuorumNetworkManager/blob/master/startQuorumBMAndBVNode.sh

**Comment by andytudhope** [comment]
As requested in slack, the `application.propoerties` file:

```
cakeshop.database.vendor=hsqldb
cakeshop.hibernate.hbm2ddl.auto=update
cakeshop.hibernate.jdbc.batch_size=20
cakeshop.jdbc.pass=sdk
cakeshop.jdbc.user=sdk
cakeshop.mvc.async.pool.queue.max=2000
cakeshop.mvc.async.pool.threads.core=250
cakeshop.mvc.async.pool.threads.max=1000
contract.poll.delay.millis=5000
contract.registry.addr=
endpoints.actuator.enabled=true
geth.auto.start=false
geth.auto.stop=false
geth.block.maker=0xca843569e3427144cead5e4d5999a3d0ccf92b8e
geth.bootnode.address=
geth.bootnode.key=
geth.bootnodes.list=
geth.cors.enabled=false
geth.cors.url=
geth.cred1=admin
geth.cred2=$2a$10$dbGiTnfK/w8MhcpIj3XgROYXRsFMlEYJRWoUYArkr8aSPypUFV25G
geth.datadir=/home/bc_admin/data/local/ethereum
geth.db.enabled=true
geth.identity=bc_admin
geth.log=/logs
geth.mining=true
geth.networkid=91351
geth.node.port=30303
geth.params.extra=
geth.rpcapi.list=admin,db,eth,debug,miner,net,shh,txpool,personal,web3
geth.url=http\://192.168.122.10\:20000
geth.verbosity=
geth.vote.account=0x0fbdc686b912d7722dc86510934589e0aaf3b55a
geth.vote.contract.addr=0x0000000000000000000000000000000000000020
management.context-path=/manage
management.security.enabled=false
security.basic.enabled=false
security.ignored=/**
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
spring.main.banner-mode=off
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
```
